//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PmSim.Frontend.App.Properties.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizationGameOptionsScreen {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationGameOptionsScreen() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PmSim.Frontend.App.Properties.Localizations.LocalizationGameOptionsScreen", typeof(LocalizationGameOptionsScreen).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По умолчанию.
        /// </summary>
        public static string ButtonDefault {
            get {
                return ResourceManager.GetString("ButtonDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начать!.
        /// </summary>
        public static string ButtonStart {
            get {
                return ResourceManager.GetString("ButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки партии.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аукцион (сек.).
        /// </summary>
        public static string TextBlockAuctionRealTime {
            get {
                return ResourceManager.GetString("TextBlockAuctionRealTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ботов.
        /// </summary>
        public static string TextBlockBots {
            get {
                return ResourceManager.GetString("TextBlockBots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор предыстории (сек.).
        /// </summary>
        public static string TextBlockChoosingBackgroundRealTime {
            get {
                return ResourceManager.GetString("TextBlockChoosingBackgroundRealTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключение (сек.).
        /// </summary>
        public static string TextBlockConnectionRealTime {
            get {
                return ResourceManager.GetString("TextBlockConnectionRealTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дипломатия (сек.).
        /// </summary>
        public static string TextBlockDiplomacyRealTime {
            get {
                return ResourceManager.GetString("TextBlockDiplomacyRealTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Происшествие (сек.).
        /// </summary>
        public static string TextBlockIncidentRealTime {
            get {
                return ResourceManager.GetString("TextBlockIncidentRealTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игроков.
        /// </summary>
        public static string TextBlockPlayers {
            get {
                return ResourceManager.GetString("TextBlockPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действий спринта.
        /// </summary>
        public static string TextBlockSprintActionsNumber {
            get {
                return ResourceManager.GetString("TextBlockSprintActionsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спринт (сек.).
        /// </summary>
        public static string TextBlockSprintRealTime {
            get {
                return ResourceManager.GetString("TextBlockSprintRealTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стартовый капитал.
        /// </summary>
        public static string TextBlockStartUpCapital {
            get {
                return ResourceManager.GetString("TextBlockStartUpCapital", resourceCulture);
            }
        }
    }
}
